### ISSUE TITLE
Formatting functions not thread safe

### ISSUE THREAD

**Issue by mariyamkhalid** [golang-module/carbon#180]
Hello,

I encountered an issue with the following code:
```go
package main

import (
	"fmt"
	"time"

	"github.com/golang-module/carbon/v2"
)

func say(rawTime carbon.Carbon) {
	formatted := rawTime.ToShortMonthString()
	fmt.Println(formatted)
}

func main() {
	rawTime := carbon.Parse("2022-05-01", carbon.UTC)
	go say(rawTime)
	go say(rawTime)
	go say(rawTime)
	time.Sleep(100 * time.Millisecond)
}
```

golang version: 1.19

carbon version:v2.2.3

time zone:  UTC

I expected to get:

```
May
May
May
```

But I actually get:

```
fatal error: concurrent map read and map write

goroutine 11 [running]:
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xed9ffc480, 0x0}, 0x0, 0x250b420, 0xc00061a940, {0x0, 0x0}}, {0x0, 0x0, ...})
        /Users/mariyam.khalid/workspace/ntbue-insights-service/vendor/github.com/golang-module/carbon/v2/outputer.go:61 +0x1ed
tableau/ntbue-insights-service/internal/facts_test.say({{0x0, 0xed9ffc480, 0x0}, 0x0, 0x250b420, 0xc00061a940, {0x0, 0x0}})
```

Thanks!

**Comment by gouguoyin** [comment]
The next version will fix.

**Comment by gouguoyin** [comment]
Fixed in version 2.2.4

**Comment by mariyamkhalid** [comment]
Thanks! I think that fixed some issues.
But I'm still getting concurrent read write panics ..

`import (
	"fmt"
	"time"

	"github.com/golang-module/carbon/v2"
)

func say(rawTime carbon.Carbon) {
	formatted := rawTime.ToShortMonthString()
	fmt.Println(formatted)
}

func main() {
	cDate := carbon.Parse("2022-12-01")
	for i := 0; i < 30; i++ {
		go say(cDate)
	}
	time.Sleep(100 * time.Millisecond)
}
`

**Comment by davidjsimpson98** [comment]
This problem still happens. I can reproduce it with version 2.2.5 and 2.3.5, using [the sample program provided by Mariyam on Aug 22](https://github.com/golang-module/carbon/issues/180#issuecomment-1688470607).

**Comment by ooumonidesi** [comment]
<img width="789" alt="image" src="https://github.com/golang-module/carbon/assets/156647858/4b80a241-f99f-4660-bce3-41a590b36433">
<img width="741" alt="image" src="https://github.com/golang-module/carbon/assets/156647858/8590b7f1-d2dd-483d-a8d7-7fb3f66d576c">

**Comment by gouguoyin** [comment]
<img width="1043" alt="image" src="https://github.com/golang-module/carbon/assets/13517412/cc21f246-3c4e-4c10-837c-63a3e16d2a9a">
<img width="1049" alt="image" src="https://github.com/golang-module/carbon/assets/13517412/3a2c0c8c-ab64-4fe3-af42-cbd6213d354d">

**Comment by davidjsimpson98** [comment]
Run the program several times. I found that the concurrent map access error happens about half of the time. I was also running it from the command line with `go run`.

**Comment by davidjsimpson98** [comment]
```
$ go run ./carbon-test.go
fatal error:
concurrent map read and map write
Dec

goroutine 22 [running]:
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({0x0, {0x0, 0xedb1a5600, 0x11a66e0}, 0x0, 0x11a66e0, 0xc000126040, {0x0, 0x0}}, {0x0, ...})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:61 +0x1f0
main.say({0x0, {0x0, 0xedb1a5600, 0x11a66e0}, 0x0, 0x11a66e0, 0xc000126040, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x9c
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 1 [sleep]:
time.Sleep(0x5f5e100)
	/Users/david/.goenv/versions/1.21/src/runtime/time.go:195 +0x125
main.main()
	/Users/david/testing/carbon-test.go:20 +0x1b9

goroutine 18 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 19 [runnable]:
time.(*Location).get(0x11a66e0?)
	/Users/david/.goenv/versions/1.21/src/time/zoneinfo.go:87 +0x67
time.Time.abs({0x0, 0xedb1a5600, 0x11a66e0})
	/Users/david/.goenv/versions/1.21/src/time/time.go:465 +0x3f
time.Time.date({0x10c6a7c?, 0x3?, 0x11a66e0?}, 0xc8?)
	/Users/david/.goenv/versions/1.21/src/time/time.go:962 +0x1d
time.Time.Month(...)
	/Users/david/.goenv/versions/1.21/src/time/time.go:517
github.com/golang-module/carbon/v2.Carbon.MonthOfYear({0x0, {0x0, 0xedb1a5600, 0x11a66e0}, 0x0, 0x11a66e0, 0xc000126040, {0x0, 0x0}})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/getter.go:34 +0x1e5
github.com/golang-module/carbon/v2.Carbon.Month(...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/getter.go:262
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({0x0, {0x0, 0xedb1a5600, 0x11a66e0}, 0x0, 0x11a66e0, 0xc000126040, {0x0, 0x0}}, {0x0, ...})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:64 +0x2ce
main.say({0x0, {0x0, 0xedb1a5600, 0x11a66e0}, 0x0, 0x11a66e0, 0xc000126040, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x9c
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 20 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 21 [runnable]:
internal/poll.(*FD).Write(0xc000124060, {0xc0000121d0, 0x4, 0x8})
	/Users/david/.goenv/versions/1.21/src/internal/poll/fd_unix.go:385 +0x449
os.(*File).write(...)
	/Users/david/.goenv/versions/1.21/src/os/file_posix.go:46
os.(*File).Write(0xc000122008, {0xc0000121d0?, 0x4, 0xc000116ef8?})
	/Users/david/.goenv/versions/1.21/src/os/file.go:183 +0x51
fmt.Fprintln({0x110e108, 0xc000122008}, {0xc000116f68, 0x1, 0x1})
	/Users/david/.goenv/versions/1.21/src/fmt/print.go:305 +0x6f
fmt.Println(...)
	/Users/david/.goenv/versions/1.21/src/fmt/print.go:314
main.say({0x0, {0x0, 0xedb1a5600, 0x11a66e0}, 0x0, 0x11a66e0, 0xc000126040, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:12 +0xd8
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 23 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 24 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 25 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 26 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 27 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 28 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 29 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 30 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 31 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc000120018)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000126040, {0x10e1db8, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:55 +0x3f
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({0x0, {0x0, 0xedb1a5600, 0x11a66e0}, 0x0, 0x11a66e0, 0xc000126040, {0x0, 0x0}}, {0x0, ...})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:59 +0x1cc
main.say({0x0, {0x0, 0xedb1a5600, 0x11a66e0}, 0x0, 0x11a66e0, 0xc000126040, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x9c
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 32 [runnable]:
fmt.glob..func1()
	/Users/david/.goenv/versions/1.21/src/fmt/print.go:147 +0x1a
sync.(*Pool).Get(0x11a2740)
	/Users/david/.goenv/versions/1.21/src/sync/pool.go:151 +0xb1
fmt.newPrinter()
	/Users/david/.goenv/versions/1.21/src/fmt/print.go:152 +0x1e
fmt.Fprintln({0x110e108, 0xc000122008}, {0xc000159768, 0x1, 0x1})
	/Users/david/.goenv/versions/1.21/src/fmt/print.go:303 +0x30
fmt.Println(...)
	/Users/david/.goenv/versions/1.21/src/fmt/print.go:314
main.say({0x0, {0x0, 0xedb1a5600, 0x11a66e0}, 0x0, 0x11a66e0, 0xc000126040, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:12 +0xd8
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 33 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 34 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 35 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 36 [runnable]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc000120018)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000126040, {0x10e1db8, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:55 +0x3f
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({0x0, {0x0, 0xedb1a5600, 0x11a66e0}, 0x0, 0x11a66e0, 0xc000126040, {0x0, 0x0}}, {0x0, ...})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:59 +0x1cc
main.say({0x0, {0x0, 0xedb1a5600, 0x11a66e0}, 0x0, 0x11a66e0, 0xc000126040, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x9c
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 37 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 38 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 39 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 40 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 41 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 42 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 43 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 44 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 45 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105

goroutine 46 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x105
exit status 2
```

**Comment by davidjsimpson98** [comment]
```
$ go run ./carbon-test.go

fatal error: concurrent map read and map write
Dec
fatal error: concurrent map read and map write
fatal error: concurrent map read and map write

goroutine 34 [running]:
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:69 +0x149
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 1 [sleep]:
time.Sleep(0x5f5e100)
	/Users/david/.goenv/versions/1.21/src/runtime/time.go:195 +0x125
main.main()
	/Users/david/testing/carbon-test.go:20 +0x11c

goroutine 6 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 7 [runnable]:
reflect.mapassign_faststr0(0x10ca100, 0x10c5bc0?, {0xc0001800ba?, 0x110f7a0?}, 0x10c5bc0?)
	/Users/david/.goenv/versions/1.21/src/runtime/map.go:1376 +0x25
reflect.mapassign_faststr(0x10c5bc0?, 0xc000182010?, {0xc0001800ba, 0x6}, 0x19?)
	/Users/david/.goenv/versions/1.21/src/reflect/value.go:3837 +0xa9
reflect.Value.SetMapIndex({0x10ca100?, 0xc0000240a0?, 0x97?}, {0x10c5bc0, 0xc0001820e0, 0x98}, {0x10c5bc0, 0xc000182010, 0x198})
	/Users/david/.goenv/versions/1.21/src/reflect/value.go:2402 +0x225
encoding/json.(*decodeState).object(0xc000186000, {0x10c4c40?, 0xc0000240a0?, 0x1010000000010?})
	/Users/david/.goenv/versions/1.21/src/encoding/json/decode.go:797 +0x13c5
encoding/json.(*decodeState).value(0xc000186000, {0x10c4c40?, 0xc0000240a0?, 0x1216a68?})
	/Users/david/.goenv/versions/1.21/src/encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).unmarshal(0xc000186000, {0x10c4c40?, 0xc0000240a0?})
	/Users/david/.goenv/versions/1.21/src/encoding/json/decode.go:181 +0x133
encoding/json.Unmarshal({0xc000184000, 0x2f9, 0x300}, {0x10c4c40, 0xc0000240a0})
	/Users/david/.goenv/versions/1.21/src/encoding/json/decode.go:108 +0x111
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:69 +0x18e
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 8 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 9 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 10 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 11 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 12 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 13 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 14 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 15 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 16 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 17 [running]:
	goroutine running on other thread; stack unavailable
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 18 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 19 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 20 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 22 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 23 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 24 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 25 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 26 [running]:
	goroutine running on other thread; stack unavailable
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 27 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 28 [runnable]:
main.main.func1()
	/Users/david/testing/carbon-test.go:18
runtime.goexit()
	/Users/david/.goenv/versions/1.21/src/runtime/asm_amd64.s:1650 +0x1
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 29 [runnable]:
fmt.(*buffer).writeString(...)
	/Users/david/.goenv/versions/1.21/src/fmt/print.go:108
fmt.(*fmt).padString(0x11d0468?, {0xc00018e02c, 0x3})
	/Users/david/.goenv/versions/1.21/src/fmt/format.go:110 +0x217
fmt.(*fmt).fmtS(0x100b8fe?, {0xc00018e02c?, 0x0?})
	/Users/david/.goenv/versions/1.21/src/fmt/format.go:359 +0x39
fmt.(*pp).fmtString(0xc000290000?, {0xc00018e02c?, 0xd0?}, 0x10d8100?)
	/Users/david/.goenv/versions/1.21/src/fmt/print.go:494 +0x85
fmt.(*pp).printArg(0xc000290000, {0x10c5bc0?, 0xc00028e000}, 0x76)
	/Users/david/.goenv/versions/1.21/src/fmt/print.go:741 +0x1bb
fmt.(*pp).doPrintln(0xc000290000, {0xc00020ef60?, 0x1, 0xc00011c6e8?})
	/Users/david/.goenv/versions/1.21/src/fmt/print.go:1223 +0x38
fmt.Fprintln({0x110e2c8, 0xc00004a010}, {0xc00011c760, 0x1, 0x1})
	/Users/david/.goenv/versions/1.21/src/fmt/print.go:304 +0x49
fmt.Println(...)
	/Users/david/.goenv/versions/1.21/src/fmt/print.go:314
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:12 +0x7b
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 30 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 31 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 32 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 35 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/Users/david/.goenv/versions/1.21/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00001a180)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/Users/david/.goenv/versions/1.21/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
	/Users/david/.goenv/versions/1.21/src/sync/rwmutex.go:147 +0x31
github.com/golang-module/carbon/v2.(*Language).SetLocale(0xc000024080, {0x10e11e0, 0x2})
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/language.go:56 +0x4b
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:67 +0x125
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 26 [running]:
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:69 +0x149
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78

goroutine 17 [running]:
github.com/golang-module/carbon/v2.Carbon.ToShortMonthString({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}}, ...)
	/Users/david/testing/vendor/github.com/golang-module/carbon/v2/outputer.go:69 +0x149
main.say({{0x0, 0xedb1a5600, 0x11a7c80}, 0x0, 0x0, 0x0, 0x11a7c80, 0xc000024080, {0x0, 0x0}})
	/Users/david/testing/carbon-test.go:11 +0x3f
created by main.main in goroutine 1
	/Users/david/testing/carbon-test.go:18 +0x78
exit status 2
```

**Comment by gouguoyin** [comment]
Fixed in v2.3.6

**Comment by gouguoyin** [comment]
Have you tested it and there are still any issues？

**Comment by davidjsimpson98** [comment]
I cannot reproduce the problem with v2.3.6.

**Comment by davidjsimpson98** [comment]
I cannot reproduce the problem with version v.2.3.6.
